<?php /* @var $page \CmsIr\Page\Model\Page */?>
<?php if(isset($client)): ?>
    <div class="white-wrapper clearfix">
        <div class="container">
            <h1 class="site-title"><?php echo $client->getName(); ?></h1>
            <p class="site-desc"><?php echo $client->getDescription(); ?></p>
        </div>
    </div>
<?php else: ?>
    <div class="white-wrapper clearfix">
        <div class="container">
            <?php echo $page->getContent(); ?>
        </div>
    </div>
<?php endif; ?>

<?php
    switch($slug)
    {
        case 'portfolio':
            if(isset($post))
            {
                echo $this->partial('partial/page/single-product');
            } else
            {
                echo $this->partial('partial/page/products');
            }
            $this->inlineScript()->appendFile($this->basePath().'/js/portfolio.js');
        break;
        case 'klient':
            echo $this->partial('partial/page/products');
            $this->inlineScript()->appendFile($this->basePath().'/js/portfolio.js');
        break;
        case 'o-nas':
            echo $this->partial('partial/page/about');
        break;
        case 'kontakt':
            echo $this->partial('partial/page/contact');
            $this->headLink()->appendStylesheet($this->basePath().'/css/jquery.realperson.css');

            $this->inlineScript()->appendFile($this->basePath().'/js/jquery.jigowatt.js');
            $this->inlineScript()->appendFile($this->basePath().'/js/jquery.realperson.min.js');
        break;
    }
?>