<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>

    <div class="row">
        <div class="col-md-6">
            <div class="the-box">

                <h4 class="small-title">Dane podstawowe</h4>
                <?php echo $this->formInput($form->get('id')); ?>
                <?php echo $this->formInput($form->get('realization_id')->setValue($realizationId)); ?>
                <?php echo $this->formInput($form->get('main_photo')); ?>
                <?php echo $this->formInput($form->get('filename_gallery')); ?>

                <?php echo $this->customFormHelper($form->get('name')) ?>
                <?php echo $this->customFormHelper($form->get('slug')) ?>
                <?php echo $this->customFormHelper($form->get('date')) ?>
                <?php echo $this->customFormHelper($form->get('url')) ?>
                <?php echo $this->customFormHelper($form->get('category_id')) ?>

                <div class="form-group">
                    <label><?php echo $this->formLabel($form->get('description')); ?></label>
                    <?php echo $this->formTextarea($form->get('description')); ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="the-box">

                <h4 class="small-title">Zdjęcie główne</h4>

                <div class="form-group">
                    <?php echo $this->customFormHelper($form->get('product_main_photo')); ?>
                    <a href="javascript:$('#product_main_photo').uploadifive('upload')" class="btn btn-facebook">Rozpocznij upload</a>
                    <!--    <a href="javascript:$('#upload').uploadifive('clearQueue')" class="btn btn-warning">Anuluj wszystkie</a>-->
                    <div id="queue"></div>
                    <div class="files"></div>
                </div>

                <h4 class="small-title">Galeria</h4>

                <div class="form-group">
                    <?php echo $this->customFormHelper($form->get('product_files')); ?>
                    <a href="javascript:$('#product_files').uploadifive('upload')" class="btn btn-facebook">Rozpocznij upload</a>
                    <a href="javascript:$('#product_files').uploadifive('clearQueue')" class="btn btn-warning">Anuluj wszystkie</a>
                    <div id="queue_2"></div>
                    <div class="files_2">
                        <?php if(!empty($productFiles)): ?>
                            <?php /** @var $file \CmsIr\Product\Model\ProductFile */ ?>
                            <?php foreach($productFiles as $file): ?>
                                <div id="<?php echo $file->getId(); ?>" class="deletePhoto">
                                    <i class="fa fa-times" data-toggle="tooltip" title="Usuń zdjęcie"></i>
                                    <img src="/files/product/<?php echo $file->getFilename(); ?>" alt="<?php echo $file->getFilename(); ?>" class="thumb" />
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="the-box">
                <div class="input-group col-sm-12 text-right">
                    <a class="btn btn-default" href="<?php echo $this->url('realization-list/product-list', array('realization_id' => $realizationId)); ?>">Anuluj</a> &nbsp
                    <?php echo $this->formInput($form->get('submit')); ?>
                </div>
            </div>
        </div>
    </div>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/summernote.min.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/product.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/uploadifive.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/datepicker.min.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/bootstrap-datepicker.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/summernote.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.uploadifive.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/product-form.js'); ?>