<?php
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
?>

<div class="row">
    <div class="col-md-6">
        <div class="the-box">
            <?php echo $this->formInput($form->get('id')); ?>

            <h4 class="small-title">Dane podstawowe</h4>
            <?php echo $this->customFormHelper($form->get('name')) ?>
            <?php echo $this->customFormHelper($form->get('slug')) ?>
            <?php echo $this->customFormHelper($form->get('date')) ?>
            <?php echo $this->customFormHelper($form->get('client_id')) ?>

        </div>
    </div>
    <div class="col-md-6">
        <div class="the-box">
            <h4 class="small-title">Opis</h4>

            <div class="form-group">
                <label><?php echo $this->formLabel($form->get('description')); ?></label>
                <?php echo $this->formTextarea($form->get('description')); ?>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <div class="input-group col-sm-12 text-right">
                <a class="btn btn-default" href="<?php echo $this->url('realization-list'); ?>">Anuluj</a> &nbsp
                <?php echo $this->formInput($form->get('submit')); ?>
            </div>
        </div>
    </div>
</div>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/summernote.min.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/product.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/datepicker.min.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/bootstrap-datepicker.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/summernote.min.js'); ?>