<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Sample web-ir website')) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        // MAIN CSS (REQUIRED ALL PAGE)
                        ->prependStylesheet($this->basePath() . '/css/main-style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/owl.carousel.css')
                        ->prependStylesheet($this->basePath() . '/css/jollyicons.css')
                        ->prependStylesheet($this->basePath() . '/css/prettyPhoto.css')
                        ->prependStylesheet($this->basePath() . '/css/cubeportfolio.min.css')


        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>

    </head>
    <body class="tooltips">

    <div class="animationload">
        <div class="loader">Loading...</div>
    </div>

    <div id="wrapper">

        <?php echo $this->partial('partial/layout/header'); ?>
        <?php echo $content; ?>
        <?php echo $this->partial('partial/layout/footer'); ?>

    </div>
    <?php echo $this->inlineScript()
                    ->prependFile($this->basePath() . '/js/jquery.cubeportfolio.min.js')
                    ->prependFile($this->basePath() . '/js/custom.js')
                    ->prependFile($this->basePath() . '/js/owl.carousel.js')
                    ->prependFile($this->basePath() . '/js/jquery.prettyPhoto.js')
                    ->prependFile($this->basePath() . '/js/retina.js')
                    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                    ->prependFile($this->basePath() . '/js/jquery.js')
    ?>

    </body>
</html>
