<style>
    #map-canvas {
        width: 100%;
        height: 400px;
    }
</style>

<script src="https://maps.googleapis.com/maps/api/js"></script>

<div class="page-wrapper clearfix">
    <div class="container">

        <div class="row">
            <div class="col-lg-6 col-md-6 col-xs-12">
                <div class="media single-work GrayScale">
<!--                    <img src="/img/map.png" alt="" class="img-responsive">-->
                    <div id="map-canvas"></div>
                </div><!-- end media -->
            </div><!-- end col -->

            <div class="col-lg-6 col-md-6 col-xs-12">
                <div class="contact-widget fadeeffect clearfix">
                    <div id="message"></div>
                    <form id="comments_form" action="/contact-form" name="contactform" method="post">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <label>Imię</label>
                            <input type="text" name="comments_form_name" id="name" class="form-control" placeholder="">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <label>Strona www</label>
                            <input type="text" name="website" id="website" class="form-control" placeholder="">
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <label>Email</label>
                            <input type="text" name="email" id="email" class="form-control" placeholder="" >
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <label>Temat</label>
                            <input type="text" name="subject" id="subject" class="form-control" placeholder="">
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <label>Treść wiadomości</label>
                            <textarea class="form-control" name="comments" id="comments" rows="6" placeholder=""></textarea>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="margin-top: 23px;">
                            <input type="text" id="defaultReal" name="defaultReal" class="form-control" />
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <br>
                            <input type="submit" value="Wyślij wiadomość" id="submit" class="cbp-l-inline-view">
                        </div>
                    </form>
                </div>
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</div><!-- end portfolio -->



<?php $this->inlineScript()->captureStart() ?>

    function initialize() {
        var mapCanvas = document.getElementById('map-canvas');
        var mapOptions = {
            center: new google.maps.LatLng(52.085815, 16.645184),
            zoom: 16,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(mapCanvas, mapOptions);

var marker = new google.maps.Marker({
position: new google.maps.LatLng(52.085815, 16.645184),
map: map,
});

marker.setMap(map);
    }

    google.maps.event.addDomListener(window, 'load', initialize);



<?php $this->inlineScript()->captureEnd() ?>