<?php if(!empty($clients)) : ?>
<div class="white-wrapper clearfix">
    <div class="container">
        <div class="owl-carousel">
            <?php /* @var $client \CmsIr\Product\Model\Client */?>
            <?php foreach($clients as $client): ?>
                <?php $filename = $client->getFilename(); ?>
                <div class="item">
                    <img src="<?php echo $this->url('thumb', array('entity' => 'client', 'size' => '220x80', 'filename' => $filename)); ?>" alt="" class="img-responsive">
                </div>
            <?php endforeach; ?>
        </div>
    </div><!-- end container -->
</div><!-- end white -->
<?php endif; ?>

<div class="copyrights">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="copyright-text pull-left">
                    <p>All works © 2015 DNA Studio / ALL RIGHTS RESERVE | Please do not reproduce without the expressed written consent of DNA Studio.</p>
		    <p>DNA Studio | 64-000 Kościan, Rynek 17, Polska</p>
		    <p>tel./fax +48 655 125 814 | mobile +48 512 434 989</p>
		    <p></p>
		    <p></p>

                </div><!-- end copyright-text -->
                <div class="pull-right">
                    <div class="social">
                        <a href=https://plus.google.com/105474667690717915732/posts data-toggle="tooltip" data-placement="top" title="Google Plus"><i class="icon-googleplus"></i></a>
                        <a href=https://www.behance.net data-toggle="tooltip" data-placement="top" title="Behance"><i class="icon-behance"></i></a>
                        <a href=https://www.youtube.com/channel/UC7AG52PYa8R3Sij0_MZE3vw data-toggle="tooltip" data-placement="top" title="YouTube"><i class=" icon-youtube-3"></i></a>
                        <a class="top" href="#" data-toggle="tooltip" data-placement="top" title="Do góry"><i class="icon-up-open-1"></i></a>
                    </div><!-- end social -->

                </div>
            </div><!-- end widget -->
        </div><!-- end row -->
    </div><!-- end container -->
</div><!-- end copyrights -->