<?php if(!empty($clients)) : ?>
<div class="white-wrapper clearfix">
    <div class="container">
        <div class="owl-carousel">
            <?php /* @var $client \CmsIr\Product\Model\Client */?>
            <?php foreach($clients as $client): ?>
                <?php $filename = $client->getFilename(); ?>
                <div class="item">
                    <img src="<?php echo $this->url('thumb', array('entity' => 'client', 'size' => '220x80', 'filename' => $filename)); ?>" alt="" class="img-responsive">
                </div>
            <?php endforeach; ?>
        </div>
    </div><!-- end container -->
</div><!-- end white -->
<?php endif; ?>

<div class="copyrights">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="copyright-text pull-left">
                    <p>Designed by Jollythemes</p>
                </div><!-- end copyright-text -->
                <div class="pull-right">
                    <div class="social">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="icon-facebook"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="icon-twitter"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Google Plus"><i class="icon-googleplus"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="reddit"><i class="icon-reddit"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="vimeo"><i class="icon-vimeo"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Behance"><i class="icon-behance"></i></a>
                        <a class="top" href="#" data-toggle="tooltip" data-placement="top" title="Back to Top"><i class="icon-up-open-1"></i></a>
                    </div><!-- end social -->

                </div>
            </div><!-- end widget -->
        </div><!-- end row -->
    </div><!-- end container -->
</div><!-- end copyrights -->