<?php
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
?>

<div class="row">
    <div class="col-md-6">
        <div class="the-box">

            <h4 class="small-title">Dane podstawowe</h4>
            <?php echo $this->formInput($form->get('id')); ?>
            <?php echo $this->formInput($form->get('filename')); ?>

            <?php echo $this->customFormHelper($form->get('name')) ?>

            <div class="form-group">
                <label><?php echo $this->formLabel($form->get('description')); ?></label>
                <?php echo $this->formTextarea($form->get('description')); ?>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="the-box">

            <h4 class="small-title">Logo</h4>

            <div class="form-group">
                <?php echo $this->customFormHelper($form->get('upload')); ?>
                <a href="javascript:$('#upload').uploadifive('upload')" class="btn btn-facebook">Rozpocznij upload</a>
                <!--    <a href="javascript:$('#upload').uploadifive('clearQueue')" class="btn btn-warning">Anuluj wszystkie</a>-->
                <div id="queue"></div>
                <div class="files"></div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <div class="input-group col-sm-12 text-right">
                <a class="btn btn-default" href="<?php echo $this->url('client'); ?>">Anuluj</a> &nbsp
                <?php echo $this->formInput($form->get('submit')); ?>
            </div>
        </div>
    </div>
</div>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/summernote.min.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/product.css'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath().'/css/uploadifive.css'); ?>

<?php $this->headScript()->appendFile($this->basePath().'/js/summernote.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/jquery.uploadifive.min.js'); ?>
<?php $this->headScript()->appendFile($this->basePath().'/js/client-form.js'); ?>