<?php
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
?>

<div class="row">
    <div class="col-md-6">
        <div class="the-box">

            <h4 class="small-title">Dane podstawowe</h4>
            <?php echo $this->customFormHelper($form->get('name')) ?>

        </div>
    </div>
    <div class="col-md-6">

    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="the-box">
            <div class="input-group col-sm-12 text-right">
                <a class="btn btn-default" href="<?php echo $this->url('category-list'); ?>">Anuluj</a> &nbsp
                <?php echo $this->formInput($form->get('submit')); ?>
            </div>
        </div>
    </div>
</div>